<?php

namespace AppBundle\Repository;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAccepted()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('t')
            ->from('AppBundle:Topic', 't')
            ->where('t.accepted = 1')
            ->orderBy('t.dateAdded', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function findLastRecord()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('t')
            ->from('AppBundle:Topic', 't')
            ->setMaxResults(1)
            ->orderBy('t.id', 'DESC');

        return $qb->getQuery()->getOneOrNullResult();
    }

}
