# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.topic.service:
        class: AppBundle\Service\TopicService
        arguments: ['@doctrine.orm.entity_manager', '@topic','@swiftmailer.mailer']

    topic:
        class: AppBundle\Entity\Topic